// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0PxX6Y7O_73nK7p0Xts4crP6t-wsYna4',
    appId: '1:605896534867:web:f49f3df6ab9636562acfa6',
    messagingSenderId: '605896534867',
    projectId: 'studentsattendence-f8a5f',
    authDomain: 'studentsattendence-f8a5f.firebaseapp.com',
    storageBucket: 'studentsattendence-f8a5f.firebasestorage.app',
    measurementId: 'G-3DCS9RJR9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2r8sAmJPCnQMpn20YvPuDoIhajHioRjw',
    appId: '1:605896534867:android:74fa1686277f45912acfa6',
    messagingSenderId: '605896534867',
    projectId: 'studentsattendence-f8a5f',
    storageBucket: 'studentsattendence-f8a5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkct-WEOxZj0oVuSAlYgqzBK8O_UgTmL0',
    appId: '1:605896534867:ios:ff19baa0b97d6ff42acfa6',
    messagingSenderId: '605896534867',
    projectId: 'studentsattendence-f8a5f',
    storageBucket: 'studentsattendence-f8a5f.firebasestorage.app',
    iosBundleId: 'com.example.studentsAttendence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkct-WEOxZj0oVuSAlYgqzBK8O_UgTmL0',
    appId: '1:605896534867:ios:ff19baa0b97d6ff42acfa6',
    messagingSenderId: '605896534867',
    projectId: 'studentsattendence-f8a5f',
    storageBucket: 'studentsattendence-f8a5f.firebasestorage.app',
    iosBundleId: 'com.example.studentsAttendence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0PxX6Y7O_73nK7p0Xts4crP6t-wsYna4',
    appId: '1:605896534867:web:9e688db81d35bd762acfa6',
    messagingSenderId: '605896534867',
    projectId: 'studentsattendence-f8a5f',
    authDomain: 'studentsattendence-f8a5f.firebaseapp.com',
    storageBucket: 'studentsattendence-f8a5f.firebasestorage.app',
    measurementId: 'G-E73M63FYML',
  );
}
